# Generated by Django 4.0.1 on 2022-01-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigenere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userandmessage',
            name='Login',
        ),
        migrations.AddField(
            model_name='userandmessage',
            name='Mess',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userandmessage',
            name='UsedId',
            field=models.IntegerField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userandmessage',
            name='EncryptMessage',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
