# Generated by Django 4.0.1 on 2022-01-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigenere', '0003_delete_userandmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAndMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EncryptMessage', models.CharField(max_length=1000, null=True)),
                ('Mess', models.CharField(max_length=1000, null=True)),
                ('UsedId', models.IntegerField(max_length=1000, null=True)),
            ],
        ),
    ]
