# Generated by Django 4.0.1 on 2022-01-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vigenere', '0004_userandmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userandmessage',
            old_name='UsedId',
            new_name='UserId',
        ),
    ]
